package chapter9.databaseapps.crud;

import chapter9.databaseapps.connecttodatabase.CreateConnection;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Created by dan on 1/30/17.
 */
public class InsertIntoTable {
    static Connection connection = null;

    public int insertInto(){
        int ret = 0;
        Statement statement = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");

            connection = CreateConnection.standardConnection();
            statement = connection.createStatement();

            ret = statement.executeUpdate
                    ("INSERT INTO people " +
                            "VALUES (2, 'Grace', 'Metadjer', 25)");

            System.out.println(ret);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } finally {
            try {
                connection.close();
                statement.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return ret;
    }

    public static void main(String [] args){
        InsertIntoTable insertIntoTable = new InsertIntoTable();
        insertIntoTable.insertInto();
    }

    /**
     * executeUpdate overloaded methods
     * - int executeUpdate(String sql) - Executes given SQL statement which may INSERT, DELETE or UPDATE
     * - int executeUpdate(String sql, int autoGeneratedKeys)
     * - int executeUpdate(String sql, int[] columnIndexes)
     * - int executeUpdate(String sql, String[] columnNames)
     */
}
